### ISSUE TITLE
Limitation on object name length or some other copy issues?

### ISSUE THREAD

**Issue by billudada78** [dewittpe/qwraps2#90] opened 2020-01-29 11:46 UTC
I have a simple summary that I am using, defined as:

`by_arm_counts <- `
`      list("ARM?" =  `
`                list("Active Drug" = ~ qwraps2::n_perc(.data$ARM == "Active"), `
`                     "Placebo"  = ~ qwraps2::n_perc(.data$ARM == "Placebo")) `
`           ) `
I was getting the following errors when creating various subsets of the total data:

`Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent`

I first thought this was due to some changes in column or rownames comming from **dplyr**, but I think I have narrowed down the issue to the length of the name of my dataframes.

For example, using a data frame named _test_ I can successfullly call:
`summary_table(test,by_arm_counts)`
`test12345678912345 <- test`
`summary_table(test12345678912345,by_arm_counts)`

I run into issues when I select within the data frame.  It works for _test_:
`summary_table(test[!duplicated(test[,c('USUBJID')]),],by_arm_counts)`

But fails with the error mentioned above for _test12345678912345_:
`summary_table(test12345678912345[!duplicated(test12345678912345[,c('USUBJID')]),],by_arm_counts)`

Comparing the dataframe (in their entirety and in the selected versions) returns TRUE:
`> all.equal(test,test12345678912345) `
` [1] TRUE `
`> all.equal(test[!duplicated(test[,c('USUBJID')]),],test12345678912345[!duplicated(test12345678912345[,c('USUBJID')]),]) `
`[1] TRUE`

I am not finding any differences in the core R objects.  In fact, I can store the subset and execute with success:
`test2 <- test12345678912345[!duplicated(test12345678912345[,c('USUBJID')]),]`
`summary_table(test2[!duplicated(test2[,c('USUBJID')]),],by_arm_counts)`

Any ideas on how I may be misusing summary_table or if there an issue in the way the selected objects are being handled by qwraps2?

**Comment by dewittpe** [comment] 2020-01-29 19:01
@billudada78, thank you for posting this issue. You are correct that the
cause of the problem is in the qwraps2 code base.

A quick reproducible example to reproduce the error:

``` r
library(qwraps2)
packageVersion('qwraps2')
#> [1] '0.4.2.9000'
library(magrittr)
options(qwraps2_markup = "markdown")

set.seed(42)

by_arm_counts <-
  list("ARM?" =
       list(
            "Active Drug" = ~ qwraps2::n_perc(.data$ARM == "Active"),
            "Placebo" = ~ qwraps2::n_perc(.data$ARM == "Placebo")
           )
      )
```

build a data.frame and have two versions, one with a short name, and one with
a long name.

``` r
test12345678912345 <- test <-
  data.frame(ARM = sample(c("Active", "Placebo"), size = 200, replace = TRUE),
             USUBJID = sample(LETTERS, size = 200, replace = TRUE))
```

summary table works as expected for a simple call

``` r
summary_table(test, by_arm_counts)
#> 
#> 
#> |                         |test (N = 200) |
#> |:------------------------|:--------------|
#> |**ARM?**                 |&nbsp;&nbsp;   |
#> |&nbsp;&nbsp; Active Drug |89 (44.50%)    |
#> |&nbsp;&nbsp; Placebo     |111 (55.50%)   |
summary_table(test12345678912345, by_arm_counts)
#> 
#> 
#> |                         |test12345678912345 (N = 200) |
#> |:------------------------|:----------------------------|
#> |**ARM?**                 |&nbsp;&nbsp;                 |
#> |&nbsp;&nbsp; Active Drug |89 (44.50%)                  |
#> |&nbsp;&nbsp; Placebo     |111 (55.50%)                 |
```

omitting duplicated rows works for `test`

``` r
summary_table(test[!duplicated(test[, c("USUBJID")]), ], by_arm_counts)
#> 
#> 
#> |                         |test[!duplicated(test[, c("USUBJID")]), ] (N = 26) |
#> |:------------------------|:--------------------------------------------------|
#> |**ARM?**                 |&nbsp;&nbsp;                                       |
#> |&nbsp;&nbsp; Active Drug |11 (42.31%)                                        |
#> |&nbsp;&nbsp; Placebo     |15 (57.69%)                                        |
```

omitting duplicated rows works for `test12345678912345` results in and error

``` r
summary_table(test12345678912345[!duplicated(test12345678912345[, c("USUBJID")]), ], by_arm_counts)
#> Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
```

A workaround would be to omit the duplicated rows outside of the
`summary_table` call.

``` r
test12345678912345 %>%
  dplyr::filter(!duplicated(.data$USUBJID)) %>%
  summary_table(., by_arm_counts)
#> 
#> 
#> |                         |. (N = 26)   |
#> |:------------------------|:------------|
#> |**ARM?**                 |&nbsp;&nbsp; |
#> |&nbsp;&nbsp; Active Drug |11 (42.31%)  |
#> |&nbsp;&nbsp; Placebo     |15 (57.69%)  |
```

The cause of this error is in the `summary_table.data.frame` call were
`deparse` is using the default width.cutoff of 60. The argument passed
through `summary_table` is exceeds this limit.

``` r
nchar('test12345678912345[!duplicated(test12345678912345[, c("USUBJID")]), ]')
#> [1] 69
```

The result: `deparse` tries, and succeeds in placing a line break, and
generates a character vector with length \> 1.

``` r
foo <- function(x) {
  deparse(substitute(x), backtick = TRUE)
}

str(
    foo(test12345678912345[!duplicated(test12345678912345[, c("USUBJID")]), ])
    )
#>  chr [1:2] "test12345678912345[!duplicated(test12345678912345[, c(\"USUBJID\")]), " ...
```

A fix for this will be to add `nlines = 1L` to the `deparse` calls.

``` r
foo <- function(x) {
  deparse(substitute(x), nlines = 1L, backtick = TRUE)
}

str(
    foo(test12345678912345[!duplicated(test12345678912345[, c("USUBJID")]), ])
    )
#>  chr "test12345678912345[!duplicated(test12345678912345[, c(\"USUBJID\")]), "
```

I will be posting the patch to kill this bug shortly.

<sup>Created on 2020-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dewittpe** [comment] 2020-01-29 19:12
``` r
library(qwraps2)
packageVersion('qwraps2')
#> [1] '0.4.2.9001'
library(magrittr)
options(qwraps2_markup = "markdown")

set.seed(42)

by_arm_counts <-
  list("ARM?" =
       list(
            "Active Drug" = ~ qwraps2::n_perc(.data$ARM == "Active"),
            "Placebo" = ~ qwraps2::n_perc(.data$ARM == "Placebo")
           )
      )

test12345678912345 <- test <-
  data.frame(ARM = sample(c("Active", "Placebo"), size = 200, replace = TRUE),
             USUBJID = sample(LETTERS, size = 200, replace = TRUE))
```

summary table works as expected

``` r
summary_table(test, by_arm_counts)
#> 
#> 
#> |                         |test (N = 200) |
#> |:------------------------|:--------------|
#> |**ARM?**                 |&nbsp;&nbsp;   |
#> |&nbsp;&nbsp; Active Drug |89 (44.50%)    |
#> |&nbsp;&nbsp; Placebo     |111 (55.50%)   |
summary_table(test12345678912345, by_arm_counts)
#> 
#> 
#> |                         |test12345678912345 (N = 200) |
#> |:------------------------|:----------------------------|
#> |**ARM?**                 |&nbsp;&nbsp;                 |
#> |&nbsp;&nbsp; Active Drug |89 (44.50%)                  |
#> |&nbsp;&nbsp; Placebo     |111 (55.50%)                 |
summary_table(test[!duplicated(test[, c("USUBJID")]), ], by_arm_counts)
#> 
#> 
#> |                         |test[!duplicated(test[, c("USUBJID")]), ] (N = 26) |
#> |:------------------------|:--------------------------------------------------|
#> |**ARM?**                 |&nbsp;&nbsp;                                       |
#> |&nbsp;&nbsp; Active Drug |11 (42.31%)                                        |
#> |&nbsp;&nbsp; Placebo     |15 (57.69%)                                        |
summary_table(test12345678912345[!duplicated(test12345678912345[, c("USUBJID")]), ], by_arm_counts)
#> 
#> 
#> |                         |test12345678912345[!duplicated(test12345678912345[, c("USUBJID")]),  (N = 26) |
#> |:------------------------|:-----------------------------------------------------------------------------|
#> |**ARM?**                 |&nbsp;&nbsp;                                                                  |
#> |&nbsp;&nbsp; Active Drug |11 (42.31%)                                                                   |
#> |&nbsp;&nbsp; Placebo     |15 (57.69%)                                                                   |

test12345678912345 %>%
  dplyr::filter(!duplicated(.data$USUBJID)) %>%
  summary_table(., by_arm_counts)
#> 
#> 
#> |                         |. (N = 26)   |
#> |:------------------------|:------------|
#> |**ARM?**                 |&nbsp;&nbsp; |
#> |&nbsp;&nbsp; Active Drug |11 (42.31%)  |
#> |&nbsp;&nbsp; Placebo     |15 (57.69%)  |
```

<sup>Created on 2020-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed as completed** 2020-01-29 19:13 UTC
Labels: bug

**Comment by dewittpe** [comment] 2020-01-29 19:15
@billudada78 

You should be able to get a version of qwraps2 which will work for your use case via

```r
remotes::install_github("dewittpe/qwraps2")
```

I've bumped the dev version from 0.4.2.9000 to 0.4.2.9001 to make this bug fix.

**Comment by billudada78** [comment] 2020-01-31 10:09
@dewittpe 
Thanks so much!  Glad to have helped identify a difficult-to-encounter and difficult-to-pin-down bug.
